export { default as Home } from "./home"
export { default as About } from "./about"
export { default as Blogs } from "./blogs"
export { default as Editor } from "./edtior"
export { default as Studio } from "./studio"
